### ISSUE TITLE
add some kind of todo list

### ISSUE THREAD

**Issue by timglabisch** [jmjoy/fastcgi-client-rs#1]
can you add some kind list of open todo's / issues?

**Comment by jmjoy** [comment]
@timglabisch What features do you want to this crate provide?

**Comment by nico-abram** [comment]
Would it make sense for this crate to support named pipes on windows?

**Comment by jmjoy** [comment]
> Would it make sense for this crate to support named pipes on windows?

I don’t work under Windows very much. If there is a crate named pipe that implements <AsyncRead + AsyncWrite + Send + Sync + Unpin>, there is no problem.
