### ISSUE TITLE
A bug existed in meta.rs write_to_stream_batches

### ISSUE THREAD

**Issue by AlexZhao** [jmjoy/fastcgi-client-rs#3]
Hi,
there is a bug existed in write_to_stream_batches,
if the reuqest's body to CGI which is larger than 65535, the request will handing there forever. it can be changed as below which marked as bold and /

impl Header {
    pub(crate) fn write_to_stream_batches<F>(
        r#type: RequestType,
        request_id: u16,
        writer: &mut dyn Write,
        content: &mut dyn Read,
        before_write: Option<F>,
    ) -> io::Result<()>
    where
        F: Fn(Header) -> Header,
    {
        let mut buf: [u8; MAX_LENGTH] = [0; MAX_LENGTH];
        let mut had_writen = false;

        loop {
            let read = content.read(&mut buf)?;
            **_if had_writen && read == 0 {_**
                break;
            }

**Comment by jmjoy** [comment]
Thanks, I see see.
